controller_list:
  - name: fake_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_gripper_controller
    joints:
      - gripper_joint
      - left_clamp_joint
      - left_rod_joint
      - right_clamp_joint
      - right_rod_joint